version: 2
updates:
  - package-ecosystem: "npm" # Use "npm" for pnpm projects
    directory: "/" # Location of package.json (root directory)
    schedule:
      interval: "weekly" # Check for updates weekly
    target-branch: "main" # Target the main branch for updates
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10 # Limit the number of open PRs
    labels:
      - "dependencies" # Add a label to Dependabot PRs
      - "priority: high" # Add another label (ensure it exists in your repo)
    reviewers:
      - "king101-bit" # Add reviewers for Dependabot PRs
    assignees:
      - "king101-bit" # Assign Dependabot PRs to specific users
